### ISSUE TITLE
can't seem to easily build on OS X

### ISSUE THREAD

**Issue by mattetti** [moovweb/gokogiri#14]
The README is obviously outdated since the makefile is gone, but I still didn't manage to build/install on Mountain Lion:

https://gist.github.com/4383203

I installed libxml2 from homebrew, updated the xpath import statement to reflect the path of the brew files.
Tried to build and go some error.

An updated readme would be very appreciated since this lib seems very useful.

Thanks,
- Matt

**Comment by chuckhutchinson2** [comment]
fyi - I had this problem to and needed to brew install pkg-config 

See https://github.com/lestrrat/go-libxml2/issues/23
