### ISSUE TITLE
How do I parse xml with a namespace?

### ISSUE THREAD

**Issue by ghost** [moovweb/gokogiri#77]
Read through everything but still not understanding how to parse xml with a namespace. var b parses correctly but I can't figure out how to parse var a below:

package main

import (
    "github.com/moovweb/gokogiri"
    "github.com/moovweb/gokogiri/xpath"
    "log"
)

func main() {
    log.SetFlags(log.Lshortfile)
    doc, _ := gokogiri.ParseXml([]byte(a))
    defer doc.Free()
    doc.SetNamespace("", "http://example.com/this")
    x := xpath.Compile(".//NodeA/NodeB")
    groups, err := doc.Search(x)
    log.Println(groups)
    if err != nil {
        log.Println(err)
    }
    for i, group := range groups {
        log.Println(i, group)
    }
}

var a = `<?xml version="1.0" ?><NodeA xmlns="http://example.com/this"><NodeB>thisthat</NodeB></NodeA>`
var b = `<?xml version="1.0" ?><NodeA><NodeB>thisthat</NodeB></NodeA>`

**Comment by opoudjis** [comment]
Still not documented, even after moving across to the jbowtie fork.

See https://stackoverflow.com/questions/27474239/how-do-i-parse-xml-with-a-namespace-using-gokogiri-libxml2
